go back to previous nvim-lspconfig version
https://github.com/neovim/nvim-lspconfig/pull/4083 broke angular.
I got the following error:

```
[ERROR][2025-11-03 14:00:55] ...p/_transport.lua:36	"rpc"	"ngserver"	"stderr"	"/home/sebastian/.local/share/nvim/mason/packages/angular-language-server/node_modules/@angular/language-server/index.js:220289
       throw new Error(`Failed to resolve '${packageName}' with minimum version '${minVersion}' from ` + JSON.stringify(probeLocations, null, 2));
       ^

       Error: Failed to resolve '@angular/language-service' with minimum version '15.0' from [
         \"/home/sebastian/Dev/project-2/node_modules/@angular/language-server/node_modules\"
       ]
    at resolveWithMinVersion (/home/sebastian/.local/share/nvim/mason/packages/angular-language-server/node_modules/@angular/language-server/index.js:220289:13)
    at resolveNgLangSvc (/home/sebastian/.local/share/nvim/mason/packages/angular-language-server/node_modules/@angular/language-server/index.js:220340:14)
    at main (/home/sebastian/.local/share/nvim/mason/packages/angular-language-server/node_modules/@angular/language-server/index.js:220366:54)
    at Object.<anonymous> (/home/sebastian/.local/share/nvim/mason/packages/angular-language-server/node_modules/@angular/language-server/index.js:220398:1)
    at Module._compile (node:internal/modules/cjs/loader:1706:14)
    at Object..js (node:internal/modules/cjs/loader:1839:10)
    at Module.load (node:internal/modules/cjs/loader:1441:32)
    at Function._load (node:internal/modules/cjs/loader:1263:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:237:24)

Node.js v22.20.0
"
```